# taken from http://rosalind.info/problems/subs/

# given two DNA strings s and t, find all locations of t as a substring of s

#s = 'GCTTCCCATCTTCCCACTTCCCACTTCCCACCCATGGGTCCTTCCCAGCAACCGCTTCCCACTTCCCAACTTCCCACTTCCCACATTGAATCTTCCCACACTTCCCATCTTCCCAGGCATTCATCCCTTCCCACAACCTTCCCAGGCTTCCCAGCTGCTTGCTTCCCATCTTCCCATCTTCCCACGCTAGCTTCCCAGTTCCTTCCCACTATCTCTTCCCAGCTTCCCAGTAAACGAGATTCTTCCCACCCTTCCCATGCTTCCCACTTCCCAGTTGGCTTCCCAAATCTTCCCAGCCTTCCCATCCTTCCCACTCTTCCCAGACTTCCCACTTCCCATCTTCCCACTTTGTTTCCTTCCCATCTTCCCACTTCCCAAGGAGTCTTCCCAGCTTCCCACTCGCTTCCCAAGTAATTGAGCCTTCCCACTTCCCATGTTCACTTCCCACGTGGAGTACCCCTGCATCCTTCCCACTTCCCACTTCCCACCTTCCCAGAACTTCCCAGCCTTCCCAACCTTCCCACTTCCCACTTCCCACTTCCCAATTCTCCTTCCCACTTCCCAAGACTTCCCACATCTTCCCATCAACTTCCCAGCTTCCCAACTTCCCATCTTCCCAATCCTTCCCATCCGGCTTCCCAGCTTCCCACGAGTCCTTCCCATCCTTCCCACTTCCCACTTCCCATGTCTTCCCACTTCCCAGACTTCCCACTTCCCAGCTTCCCACGGACTTCCCACACTTCCCACTTCCCACTTCCCAAGGTCTTCCCATGCTTCCCAAGCTTCCCACATCTTCCCAGCTTCCCATTAGCTTCCCACTTCCCAAGCTTCCCACTTCCCACCTTCCCAGCCCTTCCCATACTTCCCACTTCCCACCTTCCCAGCTTCCCA'
#t = 'CTTCCCACT'

with open('rosalind_subs.txt', 'r') as file:
    f = file.read().splitlines()
    s = str(f[0])
    t = str(f[1])

import regex as re
ans = []

for i in re.finditer(t, s, overlapped=True):
    position = str(i.start() + 1)
    print(position)
    ans.append(position)

final_answer = ' '.join(ans)
print(final_answer)
